apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-to-backend
spec:
  podSelector:
    matchLabels:
      app: backend  
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx